# This action was derived from two main sources:
# 1) https://solutions.rstudio.com/data-science-admin/deploy/github-actions/ 
# 2) https://rstudio.github.io/renv/articles/ci.html
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches:
      - main

name: deploy-to-connect

jobs:
  deploy-to-connect:
    runs-on: macOS-latest
    env:
      APP_NAME: "biofeedback_sankey"  #edit this if you want to change the custom URL of the app
      APP_DIR: "app"  #edit this only if you change the name of the folder the Shiny R script is in
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSCONNECT_URL: ${{ secrets.RSCONNECT_URL }}
      RSCONNECT_APIKEY: ${{ secrets.RSCONNECT_APIKEY }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
      
      - name: Install rsconnect
        shell: Rscript {0}
        run: |
          if (!requireNamespace("packrat", quietly = TRUE)) install.packages("packrat")
          if (!requireNamespace("rsconnect", quietly = TRUE)) install.packages("rsconnect")
          if (!requireNamespace("Cairo", quietly = TRUE)) install.packages("Cairo")
          options(shiny.usecairo = TRUE) #to fix bad aliasing in plots

# For more detailed documentation on the following steps see 
# https://github.com/rstudio/actions/tree/main/connect-publish
          
      - name: Generate manifest.json
        run: |
          rsconnect::writeManifest(appDir = "${{ env.APP_DIR }}")
        shell: Rscript {0}

      - name: Deploy to RStudio Connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: https://${{ env.RSCONNECT_APIKEY }}@${{ env.RSCONNECT_URL }}
          access-type: all
          show-logs: true
          force: true
          dir: ${{ env.APP_DIR }}/:${{ env.APP_NAME }}
          require-vanity-path: true
